# @see https://docs.travis-ci.com/user/docker/
language: go

services:
  - docker

script:
  - make generate test

# https://cjolowicz.github.io/posts/hosting-a-hugo-blog-on-github-pages-with-travis-ci/
deploy:
  - provider: script
    script: bash deploy.sh
    skip_cleanup: true
    on:
      branch: source  